spring:
  application:
    name: wrbi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/wrbi
    url: jdbc:mysql://118.25.228.235:3307/wrbi
    username: root
    password: 123
  # Redis 配置
  redis:
    database: 0
#    host: localhost
    host: 118.25.228.235
    port: 6379
    timeout: 5000
    password: 123123
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  rabbitmq:
#    host: localhost
    host: 118.25.228.235
    port: 5672
    password: guest
    username: guest
server:
  #  address: localhost
  address: 0.0.0.0
  port: 9090
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# jwt配置
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-jwt-test #jwt加解密使用的密钥
  expiration: 360000000 #JWT的超时时间
  tokenHead: Bearer #JWT负载中拿到的开头
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# AI配置
yuapi:
  client:
    access-key: 2hnxborhmshj5mapxdfnh3f4pjhporei
    secret-key: n8z72ui79g2j35u1lbmpsnolffzzc86o
xunfei:
  client:
    appid: 640ef180
    apiSecret: MDBkYzczMGI2NjIyNDg3YmI3ZTU3ZWU1
    apiKey: e5046cc7d1288c59bf30cbb282a9b88c
